# Generated by Django 5.0.2 on 2024-02-12 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="water_meter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_code", models.CharField(max_length=2)),
                ("data_length", models.CharField(blank=True, max_length=2)),
                ("meter_serial", models.CharField(default="varchar", max_length=12)),
                ("cumulative_volume", models.CharField(blank=True, max_length=8)),
                ("alarm", models.CharField(blank=True, max_length=6)),
                ("diagnosis", models.CharField(blank=True, max_length=6)),
                ("valve_status", models.CharField(blank=True, max_length=2)),
                ("checksum", models.CharField(blank=True, max_length=4)),
                ("end_code", models.CharField(max_length=2)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="watter_meter_old",
            fields=[
                (
                    "water_meter_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="project.water_meter",
                    ),
                ),
                ("hourly_frozen_data", models.CharField(blank=True, max_length=50)),
                ("valve_opening", models.BooleanField()),
                ("voltage_sampling_value", models.FloatField(blank=True)),
                ("reserve", models.CharField(blank=True, max_length=2)),
            ],
            bases=("project.water_meter",),
        ),
    ]
