# Generated by Django 5.0.2 on 2024-02-14 15:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="water_meter_ubication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("long", models.FloatField(max_length=10)),
                ("latitude", models.FloatField(max_length=10)),
                ("meter_serial", models.CharField(max_length=12)),
                ("efectivity", models.IntegerField(max_length=3)),
            ],
        ),
    ]
