# Generated by Django 5.0.2 on 2024-02-16 17:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0002_water_meter_ubication"),
    ]

    operations = [
        migrations.RenameField(
            model_name="water_meter_ubication",
            old_name="long",
            new_name="longitude",
        ),
    ]
